// Code generated by "stringer -type Linkage enum.go"; DO NOT EDIT.

package ir

import "fmt"

const _Linkage_name = "ExternalLinkageInternalLinkage"

var _Linkage_index = [...]uint8{0, 15, 30}

func (i Linkage) String() string {
	i -= 1
	if i < 0 || i >= Linkage(len(_Linkage_index)-1) {
		return fmt.Sprintf("Linkage(%d)", i+1)
	}
	return _Linkage_name[_Linkage_index[i]:_Linkage_index[i+1]]
}
