// Code generated by "stringer -type opcode enum.go"; DO NOT EDIT

package ir

import "fmt"

const _opcode_name = "argumentsbeginScopeendScoperesultvariable"

var _opcode_index = [...]uint8{0, 9, 19, 27, 33, 41}

func (i opcode) String() string {
	i -= 1
	if i < 0 || i >= opcode(len(_opcode_index)-1) {
		return fmt.Sprintf("opcode(%d)", i+1)
	}
	return _opcode_name[_opcode_index[i]:_opcode_index[i+1]]
}
