// Code generated by "stringer -type tok enum.go"; DO NOT EDIT.

package ir

import "fmt"

const _tok_name = "tokI8tokI16tokI32tokI64tokU8tokU16tokU32tokU64tokF32tokF64tokF128tokC64tokC128tokC256tokEllipsistokFunctokNumbertokStructtokUniontokNametokEOFtokIllegal"

var _tok_index = [...]uint8{0, 5, 11, 17, 23, 28, 34, 40, 46, 52, 58, 65, 71, 78, 85, 96, 103, 112, 121, 129, 136, 142, 152}

func (i tok) String() string {
	i -= 256
	if i < 0 || i >= tok(len(_tok_index)-1) {
		return fmt.Sprintf("tok(%d)", i+256)
	}
	return _tok_name[_tok_index[i]:_tok_index[i+1]]
}
